# scripts/create_schema.py

import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

ORACLE_USER = os.getenv("ORACLE_USER", "retail")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD", "retail")
ORACLE_DSN = os.getenv("ORACLE_DSN", "localhost:1521/XEPDB1")

DDL_STATEMENTS = [
    """
    CREATE TABLE categorias (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR2(50) NOT NULL
    )
    """,
    """
    CREATE TABLE productos (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR2(100) NOT NULL,
        categoria_id NUMBER REFERENCES categorias(id),
        precio NUMBER(10,2) NOT NULL
    )
    """,
    """
    CREATE TABLE tiendas (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR2(100),
        ciudad VARCHAR2(100)
    )
    """,
    """
    CREATE TABLE ventas (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha DATE NOT NULL,
        producto_id NUMBER REFERENCES productos(id),
        tienda_id NUMBER REFERENCES tiendas(id),
        cantidad NUMBER NOT NULL,
        total NUMBER(10,2) NOT NULL
    )
    """
]


def main():
    conn = oracledb.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=ORACLE_DSN,
    )
    cur = conn.cursor()

    for ddl in DDL_STATEMENTS:
        try:
            cur.execute(ddl)
            print("✅ Tabla creada")
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            # ORA-00955: name is already used by an existing object
            if error_obj.code == 955:
                print("ℹ️ Tabla ya existe, se omite")
            else:
                print(f"❌ Error creando tabla: {error_obj.message}")
                raise

    conn.commit()
    cur.close()
    conn.close()
    print("✅ Esquema listo")

if __name__ == "__main__":
    main()
